image: docker:latest

stages:
  - local_build

local:
  stage: local_build
  services:
    - docker:dind 
  script:
    - export ALLOWED_ACCESS_URI=$ALLOWED_ACCESS_URI
    - export BOT_ACCESS_PORT=$BOT_ACCESS_PORT
    - export BOT_ACCESS_URI=$BOT_ACCESS_URI
    - export MONGODB_URI=$MONGODB_URI
    - export MONGODB_AUTH_SOURCE=$MONGODB_AUTH_SOURCE
    - export MONGODB_USER=$MONGODB_USER
    - export MONGODB_PASSWORD=$MONGODB_PASSWORD
    - export MONGODB_DBNAME=$MONGODB_DBNAME
    - docker login -u $CI_REGISTRY_USER -p $PERS_ACCESS_TOKEN $CI_REGISTRY
    - docker pull registry.gitlab.com/yannick_isika23p4/perform-back-nodejs/perform-back-nodejs:latest
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
    - docker logout