stages:
#  - start_back
  - local_build

#image: docker:latest

#node_back:
#  stage: start_back
#  services:
#    - docker:dind
#  script:
#    - docker run registry.gitlab.com/yannick_isika23p4/perform-back-nodejs/perform-back-nodejs

local:
  stage: local_build
  image: docker:latest
  services:
    - docker:dind 
  script:
    #- export ALLOWED_ACCESS_URI=$ALLOWED_ACCESS_URI
    #- export BOT_ACCESS_PORT=$BOT_ACCESS_PORT
    #- export BOT_ACCESS_URI=$BOT_ACCESS_URI
    #- export MONGODB_URI=$MONGODB_URI
    #- export MONGODB_AUTH_SOURCE=$MONGODB_AUTH_SOURCE
    #- export MONGODB_USER=$MONGODB_USER
    #- export MONGODB_PASSWORD=$MONGODB_PASSWORD
    #- export MONGODB_DBNAME=$MONGODB_DBNAME
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE .
    - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE
    - docker logout
  #dependencies: 
  #    - node_back