stages:
  - deploy
  
prod:
  image: node:18-alpine
  stage: deploy
  script:
    - npm install
    - MONGODB_AUTH_SOURCE=$MONGODB_AUTH_SOURCE
    - export PROD_MONGODB_URI=$PROD_MONGODB_URI
    - export PROD_MONGODB_DBNAME=$PROD_MONGODB_DBNAME
    - export SPORTSDATA_API_KEY=$SPORTSDATA_API_KEY
    - export SPORTSDATA_API_KEY2=$SPORTSDATA_API_KEY2
    - export RAPIDAPI_API_KEY=$RAPIDAPI_API_KEY
    - export RAPIDAPI_API_KEY2=$RAPIDAPI_API_KEY2
    - export NEWSAPI_API_KEY=$NEWSAPI_API_KEY
    - node index.js