#image: docker:latest
#
#stages:
#  - local_build
#
#local:
#  stage: local_build
#  services:
#    - docker:dind 
#  script:
#    - export FRONT_ACCESS_URI=$FRONT_ACCESS_URI
#    - export BACK_NODE_ACCESS_PORT=$BACK_NODE_ACCESS_PORT
#    - export MONGODB_URI=$MONGODB_URI
#    - export MONGODB_AUTH_SOURCE=$MONGODB_AUTH_SOURCE
#    - export MONGODB_USER=$MONGODB_USER
#    - export MONGODB_PASSWORD=$MONGODB_PASSWORD
#    - export MONGODB_DBNAME=$MONGODB_DBNAME
#    - docker login -u $CI_REGISTRY_USER -p $PERS_ACCESS_TOKEN $CI_REGISTRY
#    - docker pull registry.gitlab.com/votre-utilisateur/votre-projet/premiere_image:latest  # Remplacez avec le chemin correct
#    - docker build -t $CI_REGISTRY_IMAGE .
#    - docker push $CI_REGISTRY_IMAGE
#    - docker logout