stages:
  - local_build

local:
  stage: local_build
  image: docker:latest
  services:
    - docker:dind 
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE .
    - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE
    - docker logout