#stages:
#  - start_back
#  - local_build

#node_back:
#  stage: start_back
#  image: my_image
#
#local:
#  stage: local_build
#  image: docker:latest
#  services:
#    - docker:dind
#  dependencies:
#    - node_back 
#  script:
#    - export FRONT_ACCESS_URI=$FRONT_ACCESS_URI
#    - export BACK_NODE_ACCESS_PORT=$BACK_NODE_ACCESS_PORT
#    - export MONGODB_URI=$MONGODB_URI
#    - export MONGODB_AUTH_SOURCE=$MONGODB_AUTH_SOURCE
#    - export MONGODB_USER=$MONGODB_USER
#    - export MONGODB_PASSWORD=$MONGODB_PASSWORD
#    - export MONGODB_DBNAME=$MONGODB_DBNAME
#    - docker login -u $CI_REGISTRY_USER -p $PERS_ACCESS_TOKEN $CI_REGISTRY
#    - docker build -t $CI_REGISTRY_IMAGE .
#    - docker push $CI_REGISTRY_IMAGE
#    - docker logout