stages:
  - start_back
  - local_build

node_back:
  stage: start_back
  image: mongo:latest
  script:
    - mongod --bind_ip_all --fork --logpath /var/log/mongod.log
    - export MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
    - export MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    - export MONGO_INITDB_DATABASE=$MONGODB_DBNAME

local:
  stage: local_build
  image: registry.gitlab.com/yannick_isika23p4/perform-back-nodejs/perform-back-nodejs
  services:
    - docker:dind 
  script:
    - export ALLOWED_ACCESS_URI=$ALLOWED_ACCESS_URI
    - export BOT_ACCESS_PORT=$BOT_ACCESS_PORT
    - export BOT_ACCESS_URI=$BOT_ACCESS_URI
    - export MONGODB_URI=$MONGODB_URI
    - export MONGODB_AUTH_SOURCE=$MONGODB_AUTH_SOURCE
    - export MONGODB_USER=$MONGODB_USER
    - export MONGODB_PASSWORD=$MONGODB_PASSWORD
    - export MONGODB_DBNAME=$MONGODB_DBNAME
    - export GPG_TTY=$(tty)
    - docker login -u $CI_REGISTRY_USER -p $PERS_ACCESS_TOKEN $CI_REGISTRY
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
    - docker logout